### ISSUE TITLE
画面の上の方のメッセージに消されたはずのゴミ箱がある

### ISSUE THREAD

**Issue by YukiYuigishi** [Growthers/Oshavery-Front#234]
[Oshavery/#14](https://github.com/Undecided-Discord/Oshavery/issues/14) より移動
- メッセージの削除ができないため、ゴミ箱を消していたはずが、そのまま残ってしまっている
- メッセージ削除をできるようにする必要がある

**Comment by Yusuke4869** [comment]
削除の確認を挟む場合、ポップアップを実装する必要あり
