### ISSUE TITLE
ディレクトリ構成の変更の提案

### ISSUE THREAD

**Issue by YukiYuigishi** [Growthers/Oshavery-Front#256]
```
atomic designにいろいろと難があったので、ファイル構成と再分割、templatesの追加をしたいと思います。
JSXと関数を分けることを目的としています
- src 
   |  -  components
   |     | - atoms
   |     |        |  - libs
   |     | - molecules
   |     |        |  - libs
   |     | - organisms
   |     |        |  - libs
   |     | - templates
   |     |        |  - libs
   |  -  libs
   |  -  styles
   |      |- componentsと同じ構成
   |  -  stores
   |  -  types
   |  -  pages
```

**Comment by sayoi341** [comment]
### 関数をどうするか意見
> JSXと関数を分けたい
わかる

しかし、コンポーネントごとにlibsを付けるとファイルが粉々になりすぎて
- メンテナンス性が下がる
- 同じ関数を使用したい場合(ex: APIのDateを表示できる形にする関数)にどこを参照すればいいかわからなくなる

ので
1. 処理を見直す
2. 関数・hooksは、src/libs・src/hooks(追加予定) に入れる。

（ibsファイル、今すっからかんだから増やしてもよさそう）

**Comment by sayoi341** [comment]
もしかしたら、hooksに関数を書いて、それをエクスポートして各コンポーネントから使用できるようになるかもしれない

**Comment by YukiYuigishi** [comment]
> メンテナンス性が下がる
> 同じ関数を使用したい場合(ex: APIのDateを表示できる形にする関数)にどこを参照すればいいかわからなくなる

その通りなんだよなぁ
ちなみに私がこの形にしたのは、traQのディレクトリ構成をまねし用としたから(あっちはVueだけど

**Comment by sayoi341** [comment]
> ちなみに私がこの形にしたのは、traQのディレクトリ構成をまねし用としたから(あっちはVueだけど
ただ、今後traQレベルまでコードが膨らむと考えると、しっかりと分類するべきではあると思う

traQのコードが全然わからないので何とも言えないのだが、分類はすべきには賛成。

ただ、現在、styles下をcomponentsと同じ構成にしてるので、分類するんだったらlibsもそれに習うべき。(**一番上の構成図には反対という意**)


ちなみに 、I do itが「atomic designを見直したい」とも言っていたので、要検討。

--- 
> あと、個人的にはディレクトリ構成を書いた貢献者向けのドキュメントを生やしたい

頑張ってください…

---

```
- src 
   |  -  components
   |     | - atoms
   |     | - molecules
   |     | - organisms
   |     | - templates
   |  -  libs
   |     | - atoms
   |     | - molecules
   |     | - organisms
   |     | - templates
   |  -  styles
   |     | - atoms
   |     | - molecules
   |     | - organisms
   |     | - templates
   |  -  stores
   |  -  types
   |  -  pages

```
うーん

**Comment by sayoi341** [comment]
てか、atomic design的に、atomsがそんな関数つかって処理してるのやばくないか？
要見直しジャマイカ…

**Comment by sayoi341** [comment]
> あとは、1関数1ファイルぐらいの感覚でバラす？

ある程度まとめておきたい。定義が厄介だけど。

atomic designの見直し・関数の再配置のために、処理の洗い出しは必須な気がしています。

**Comment by YukiYuigishi** [comment]
> 思い切ってatomic designを辞めるのもアリな気がしてきた
これは冗談として流しておいてくれると助かる
流石に今まで蓄積した財産を消し飛ばすのは良くない

**Comment by YukiYuigishi** [comment]
これを踏まえて新しくissueを立て直します
