### ISSUE TITLE
ブランチ名の修正

### ISSUE THREAD

**Issue by YukiYuigishi** [Growthers/Oshavery-Front#271]
こんな感じに変更しようと考えています。
意見と承認を下さい。
全員の承認が出た時点で変更します
```
>>>HEAD
- Geek-Edition (defalut)
- master

===========
- master 機能が出来上がるごとにマージ
- dev // 新しい機能が出来上がるごとにotherからマージ
- other 新しい機能はdevにPRするのではなく feat</新しい機能名>にPR

>>> new
```

**Comment by YukiYuigishi** [comment]
@Yusuke4869 @sayoi341 
Git-flowを採用してみたいなと考えています
https://dev.classmethod.jp/articles/introduce-git-flow/

**Comment by Yusuke4869** [comment]
👍

**Comment by YukiYuigishi** [comment]
Git-flowを導入しました。
開発陣各位はgit-flowをインストールするなど対応を行ってください。

連絡事項
- 今後はdevelopブランチで作業しましょう
- 新しい機能を追加する場合はfeature/issue#N/hogeブランチをdevelopブランチをベースブランチとして作成してください
- masterに手元でマージしないでください

コンフリクトにはくれぐれも気を付けましょう
